# Site settings
title: Capture the Journey
nav-title: Island

client:
  name: Nikon
  link: "https://www.nikon.de/de_DE/"
core-se-link: https://www.secretescapes.de/aktuelle-angebote
description: >
  Follow Secret Escapes and Nikon to the most photogenic destinations in the world. We sent 3 photo-inspired Secret Escapes colleagues along to learn from professional photographers how to get the perfect shot.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/nikon" # the subpath of your site, e.g. /blog/
img:     "/de/nikon/_assets/img"
css:     "/de/nikon/_assets/css"
js:      "/de/nikon/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed